# -*- coding: utf-8 -*-
"""mnist_fashion_ai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2rJiZeKna0H2lg1JDvEKdmWim8CwIpO
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

data = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = data.load_data()

train_images = train_images/255.0
test_images = test_images/255.0

model = keras.Sequential([
	keras.layers.Flatten(input_shape=(28,28)),
	keras.layers.Dense(128, activation='relu'),
	keras.layers.Dense(10, activation='softmax')
	])

plt.imshow(test_images[7], cmap=plt.cm.binary)
plt.show()

plt.imshow(test_images[2])
plt.show()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5)

test_lost, test_acc = model.evaluate(test_images, test_labels)

print("Accuracy: ", test_acc)

class_names = ["T-shirt/top","Trouser","Pullover","Dress",
               "Coat","Sandal","Shirt","Sneaker","Bag","Ankle Boot"]

predictions = model.predict(test_images)

for i in range(5):
  plt.grid(False)
  plt.imshow(test_images[i], cmap=plt.cm.binary)
  plt.xlabel("Actual Label: " + class_names[test_labels[i]])
  plt.title("Prediction: " + class_names[np.argmax(predictions[i])])
  plt.show()